PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../..

TARGET          = libfdt.a
SYSTEMS         = $(SYSTEMS_PLAIN)
PC_FILENAME    :=

MODE            = host

include $(PKGDIR)/lib/build/Makefile
